### PR TITLE
Exposed results of wilcoxon

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
Hi - I have made accessible the results of the wilcoxon test, such as the p-value.

### CODE REVIEW

**Comment by larsgw** [comment]
Ah, I guess that's an issue for all the tests then. Thank you.

**Comment by LucaCappelletti94** [comment]
Let me turn that into a trait then.

**Comment by LucaCappelletti94** [comment]
And done!

**Comment by larsgw** [comment]
Oh wow, that's great! Thank you so much!

**Pull request merged**
