### PR TITLE
Fixed security problem detected with cargo audit

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
Hi - the statrs you had fixed in your dependencies had a dependency (nalgebra) that had a security vulnerability. This PR updates the dependencies and removes this vulnerability.

```bash
Crate:     nalgebra
Version:   0.23.2
Title:     VecStorage Deserialize Allows Violation of Length Invariant
Date:      2021-06-06
ID:        RUSTSEC-2021-0070
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0070
Solution:  Upgrade to >=0.27.1
Dependency tree:
nalgebra 0.23.2
└── statrs 0.13.0
    └── stattest 0.0.0
        ├── statistical_comparisons 0.1.0
        └── hyperloglog-rs 0.1.56
            └── statistical_comparisons 0.1.0

error: 1 vulnerability found!
```

### CODE REVIEW

**Comment by LucaCappelletti94** [comment]
@larsgw plz do check this PR out when you have time

**Comment by larsgw** [comment]
Merged in 66df2deca19989257273fab55243e13ae67c69c6

**Comment by larsgw** [comment]
Sorry that it shows up as closed instead of merged, I wanted to rebase and change the commit message but the interface didn't allow me to do so.

**Comment by LucaCappelletti94** [comment]
No worries, do you need me to do anything or it was merged fine?

**Comment by larsgw** [comment]
It was merged fine, thank you!

**Pull request closed without merging**
